CREATE TABLE db_classes (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
data VARCHAR(222) NOT NULL,
comment text(222) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)